name: HTML Proofer Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build  # якщо ви використовуєте Jekyll, замініть на свій генератор

      - name: Run HTML-Proofer
        run: bundle exec htmlproofer ./_site --url-ignore '#about-us,#new-mobile-games,#testimonials' --disable-external
